//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestiProjekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiskelija
    {
        public int OpiskelijaID { get; set; }
        public string Koodi { get; set; }
        public string Nimi { get; set; }
        public Nullable<int> Ikä { get; set; }
        public string Osoite { get; set; }
        public string Maa { get; set; }
        public string Email { get; set; }
        public string Postinumero { get; set; }
    }
}
